language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

install:
  - travis_retry composer install --prefer-dist

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

cache:
    directories:
        - $HOME/.composer

