language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
    - php: 7
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7

before_install:
  - composer self-update

install: COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS --prefer-dist

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "7.0" ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

cache:
    directories:
        - $HOME/.composer

