language: php

php:
  - 5.5
  - 5.4
  - 5.3

install:
  - travis_retry composer install --prefer-dist

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
    directories:
        - $HOME/.composer

